name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: website
      - name: Deploy
        uses: actions/deploy-pages@v1
